# Generated by Django 6.0 on 2026-03-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprendices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprendiz',
            name='correo',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
