# Generated by Django 6.0 on 2026-03-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprendices', '0002_alter_aprendiz_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprendiz',
            name='ciudad',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
