# Generated by Django 4.2.26 on 2025-12-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('TI', 'Tarjeta de Identidad'), ('PAS', 'Pasaporte')], default='CC', max_length=3)),
                ('documento_identidad', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('correo', models.EmailField(max_length=254, null=True)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('ciudad', models.CharField(max_length=100, null=True)),
                ('direccion', models.CharField(max_length=200, null=True)),
                ('nivel_educativo', models.CharField(choices=[('TECNICO', 'Técnico'), ('TGL', 'Tegnologo'), ('PRE', 'Pregrado'), ('ESP', 'Especialidad'), ('MAE', 'Maestria'), ('DOC', 'Doctorado')], default='MAE', max_length=7)),
                ('especialidad', models.CharField(max_length=100, null=True)),
                ('anos_experiencia', models.IntegerField(null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_vinculacion', models.DateField(null=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
